Fix lib linking

diff --git a/matrace.in b/matrace.in
--- a/matrace.in
+++ b/matrace.in
@@ -17,28 +17,30 @@
 # You should have received a copy of the GNU Lesser General Public
 # License along with mutrace. If not, see <http://www.gnu.org/licenses/>.
 
-if ! TEMP=`getopt -o +dh --long frames:,debug-info,help -n matrace -- "$@"` ; then
-    exit 1
+LIB_DIR="@LIB_DIR@"
+
+if ! TEMP=$(getopt -o +dh --long frames:,debug-info,help -n matrace -- "$@"); then
+        exit 1
 fi
 
 eval set -- "$TEMP"
 
 debug_info=0
 
-while : ; do
+while :; do
         case $1 in
-                --frames)
-                        export MATRACE_FRAMES="$2"
-                        shift 2
-                        ;;
+        --frames)
+                export MATRACE_FRAMES="$2"
+                shift 2
+                ;;
 
-                -d|--debug-info)
-                        debug_info=1
-                        shift 1
-                        ;;
+        -d | --debug-info)
+                debug_info=1
+                shift 1
+                ;;
 
-                -h|--help)
-                        cat <<EOF
+        -h | --help)
+                cat <<EOF
 @PACKAGE_STRING@
 
 Usage: matrace [OPTIONS...] APPLICATION [ARGUMENTS...]
@@ -50,35 +52,35 @@ OPTIONS:
       --frames=INTEGER            Set number of frames to show in stack traces
   -d, --debug-info                Make use of debug information in stack traces
 EOF
-                        exit 0
-                        ;;
-                --)
-                        shift
-                        break
-                        ;;
+                exit 0
+                ;;
+        --)
+                shift
+                break
+                ;;
 
-                *)
-                        echo "Parsing failed!" >&2
-                        exit 1
-                        ;;
+        *)
+                echo "Parsing failed!" >&2
+                exit 1
+                ;;
         esac
 done
 
-shift $(($OPTIND-1))
+shift $(($OPTIND - 1))
 
-if [ x"$1" = x ] ; then
+if [ x"$1" = x ]; then
         echo "Please specify an application to profile!" >&2
         exit 1
 fi
 
-if [ x"$LD_PRELOAD" = x ] ; then
-        export LD_PRELOAD="libmatrace.so"
+if [ x"$LD_PRELOAD" = x ]; then
+        export LD_PRELOAD="${LIB_DIR}/libmatrace.so"
 else
-        export LD_PRELOAD="$LD_PRELOAD:libmatrace.so"
+        export LD_PRELOAD="$LD_PRELOAD:${LIB_DIR}/libmatrace.so"
 fi
 
-if [ x"$debug_info" = x1 ] ; then
-        export LD_PRELOAD="$LD_PRELOAD:libmutrace-backtrace-symbols.so"
+if [ x"$debug_info" = x1 ]; then
+        export LD_PRELOAD="$LD_PRELOAD:${LIB_DIR}/libmutrace-backtrace-symbols.so"
 fi
 
 exec "$@"
diff --git a/mutrace.in b/mutrace.in
--- a/mutrace.in
+++ b/mutrace.in
@@ -17,81 +17,88 @@
 # You should have received a copy of the GNU Lesser General Public
 # License along with mutrace. If not, see <http://www.gnu.org/licenses/>.
 
-if ! TEMP=`getopt -o +ardh --long hash-size:,frames:,locked-min:,owner-changed-min:,contended-min:,max:,mutex-order:,cond-order:,trap,help,all,debug-info -n mutrace -- "$@"` ; then
+LIB_DIR="@LIB_DIR@"
+
+if ! TEMP=$(getopt -o +ardhf --long hash-size:,frames:,locked-min:,owner-changed-min:,contended-min:,max:,mutex-order:,cond-order:,trap,help,all,debug-info,first-ld -n mutrace -- "$@"); then
     exit 1
 fi
 
 eval set -- "$TEMP"
 
 debug_info=0
+first_ld=0
 
-while : ; do
-        case $1 in
-                --hash-size)
-                        export MUTRACE_HASH_SIZE="$2"
-                        shift 2
-                        ;;
+while :; do
+    case $1 in
+    --hash-size)
+        export MUTRACE_HASH_SIZE="$2"
+        shift 2
+        ;;
 
-                --frames)
-                        export MUTRACE_FRAMES="$2"
-                        shift 2
-                        ;;
+    --frames)
+        export MUTRACE_FRAMES="$2"
+        shift 2
+        ;;
 
-                --locked-min)
-                        export MUTRACE_LOCKED_MIN="$2"
-                        shift 2
-                        ;;
+    --locked-min)
+        export MUTRACE_LOCKED_MIN="$2"
+        shift 2
+        ;;
 
-                --owner-changed-min)
-                        export MUTRACE_OWNER_CHANGED_MIN="$2"
-                        shift 2
-                        ;;
+    --owner-changed-min)
+        export MUTRACE_OWNER_CHANGED_MIN="$2"
+        shift 2
+        ;;
 
-                --contended-min)
-                        export MUTRACE_CONTENDED_MIN="$2"
-                        shift 2
-                        ;;
+    --contended-min)
+        export MUTRACE_CONTENDED_MIN="$2"
+        shift 2
+        ;;
 
-                --max)
-                        export MUTRACE_MAX="$2"
-                        shift 2
-                        ;;
+    --max)
+        export MUTRACE_MAX="$2"
+        shift 2
+        ;;
 
-                --mutex-order)
-                        export MUTRACE_SUMMARY_MUTEX_ORDER="$2"
-                        shift 2
-                        ;;
+    --mutex-order)
+        export MUTRACE_SUMMARY_MUTEX_ORDER="$2"
+        shift 2
+        ;;
 
-                --cond-order)
-                        export MUTRACE_SUMMARY_COND_ORDER="$2"
-                        shift 2
-                        ;;
+    --cond-order)
+        export MUTRACE_SUMMARY_COND_ORDER="$2"
+        shift 2
+        ;;
 
-                --trap)
-                        export MUTRACE_TRAP=1
-                        shift 1
-                        ;;
+    --trap)
+        export MUTRACE_TRAP=1
+        shift 1
+        ;;
 
-                -r|--track-rt)
-                        export MUTRACE_TRACK_RT=1
-                        shift 1
-                        ;;
+    -r | --track-rt)
+        export MUTRACE_TRACK_RT=1
+        shift 1
+        ;;
 
-                -d|--debug-info)
-                        debug_info=1
-                        shift 1
-                        ;;
+    -d | --debug-info)
+        debug_info=1
+        shift 1
+        ;;
 
-                -a|--all)
-                        export MUTRACE_LOCKED_MIN=0
-                        export MUTRACE_OWNER_CHANGED_MIN=0
-                        export MUTRACE_CONTENDED_MIN=0
-                        export MUTRACE_MAX=0
-                        shift 1
-                        ;;
+    -a | --all)
+        export MUTRACE_LOCKED_MIN=0
+        export MUTRACE_OWNER_CHANGED_MIN=0
+        export MUTRACE_CONTENDED_MIN=0
+        export MUTRACE_MAX=0
+        shift 1
+        ;;
+    -f | --first-ld)
+        first_ld=1
+        shift 1
+        ;;
 
-                -h|--help)
-                        cat <<EOF
+    -h | --help)
+        cat <<EOF
 @PACKAGE_STRING@
 
 Usage: mutrace [OPTIONS...] APPLICATION [ARGUMENTS...]
@@ -179,35 +186,43 @@ CONDITION VARIABLE ORDER COLUMN NAMES:
   nsec-wait-contended-avg         Average time condition variable was waited on
                                   by multiple threads
 EOF
-                        exit 0
-                        ;;
-                --)
-                        shift
-                        break
-                        ;;
+        exit 0
+        ;;
+    --)
+        shift
+        break
+        ;;
 
-                *)
-                        echo "Parsing failed!" >&2
-                        exit 1
-                        ;;
-        esac
+    *)
+        echo "Parsing failed!" >&2
+        exit 1
+        ;;
+    esac
 done
 
-shift $(($OPTIND-1))
+shift $(($OPTIND - 1))
 
-if [ x"$1" = x ] ; then
-        echo "Please specify an application to profile!" >&2
-        exit 1
+if [ x"$1" = x ]; then
+    echo "Please specify an application to profile!" >&2
+    exit 1
 fi
 
-if [ x"$LD_PRELOAD" = x ] ; then
-        export LD_PRELOAD="libmutrace.so"
+if [ x"$LD_PRELOAD" = x ]; then
+    export LD_PRELOAD="${LIB_DIR}/libmutrace.so"
 else
-        export LD_PRELOAD="$LD_PRELOAD:libmutrace.so"
+    if [ x"$first_ld" = x1 ]; then
+        export LD_PRELOAD="${LIB_DIR}/libmutrace.so:$LD_PRELOAD"
+    else
+        export LD_PRELOAD="$LD_PRELOAD:${LIB_DIR}/libmutrace.so"
+    fi
 fi
 
-if [ x"$debug_info" = x1 ] ; then
-        export LD_PRELOAD="$LD_PRELOAD:libmutrace-backtrace-symbols.so"
+if [ x"$debug_info" = x1 ]; then
+    if [ x"$first_ld" = x1 ]; then
+        export LD_PRELOAD="${LIB_DIR}/libmutrace-backtrace-symbols.so:$LD_PRELOAD"
+    else
+        export LD_PRELOAD="$LD_PRELOAD:${LIB_DIR}/libmutrace-backtrace-symbols.so"
+    fi
 fi
 
-exec "$@"
+"$@"
